name: amqp091-go

on:
    push:
        branches: ["*"]
    pull_request:
        branches: [main]

jobs:
    build:
        name: build/test
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version: ['oldstable', 'stable']
        services:
            rabbitmq:
                image: rabbitmq:3.11.3-alpine
                ports:
                - 5672:5672
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5
          with:
            go-version: ${{ matrix.go-version }}
            check-latest: true
        - name: Tests
          run: go test -race ./... -timeout=10s
